### ISSUE TITLE
The shape of input data

### ISSUE THREAD

**Issue by kevinhan2018** [CyberZHG/keras-octave-conv#1]
Thank you for your excellent work which inspires me a lot. Here I have one question. If the shape of original input data is (12800,3,2) in which 12800 and 3 denote the height and width, respectively, and 2 denotes the number of channels. Then there is a ValueError: The rows and columns of the higher spatial inputs should be divisible by the octave. Found (None, 12800, 3, 2) and 2. So I am wondering why the shape of inputs must be divisible by 2. While the authors of this paper said that octave convolution is a plug-and-play replacement for the vanilla convolution. Thanks!

**Comment by CyberZHG** [comment]
It cannot be "plug-and-play" because you have two outputs after octave convolution. 😹

**Comment by CyberZHG** [comment]
The divisibility makes it much easier to implement. Otherwise, you have to deal with paddings considering lots of different settings.
